### ISSUE TITLE
Can API surface CPU usage?

### ISSUE THREAD

**Issue by vyct0r** [NebN/unraid-simple-monitoring-api#1]
Firstly, great unraid app! Great documentation, I am knowledgeable but not a pro and could figure it out. Request, can the API be modified to surface CPU usage so that I can add that to homepage? I like to be able to see CPU usage on my various servers when in homepage.

**Comment by NebN** [comment]
Glad you like it @vyct0r !
This should be easy enough to implement. I'll look into it.

**Comment by chandz05** [comment]
Hello, I would like this too! Also @NebN, I didn't want to open up a whole new issue but thank you so much for this! Was about to write my own and then I saw this in the Unraid app store :)

**Comment by NebN** [comment]
I've added a [section on the readme](https://github.com/NebN/unraid-simple-monitoring-api?tab=readme-ov-file#caveat) about the accuracy of the measurements. As this affects CPU load probably more than Network, as CPU load tends to be more erratic.

**Comment by vyct0r** [comment]
Thanks for the quick turnaround. And thanks for keeping it lightweight with the implementation. I was able to add CPU with the below lines in my homepage widget:
            - field:
                cpu: load_percent
              label: CPU
              format: percent
