### ISSUE TITLE
Unraid App cannot locate conf file

### ISSUE THREAD

**Issue by holocronology** [NebN/unraid-simple-monitoring-api#18]
I installed the app today on Unraid and keep getting the following error:

`text  error  warn  system  array  login  

2024/04/08 21:59:59 ERROR Cannot read conf.yml error="read /app/conf.yml: is a directory"

** Press ANY KEY to close this window ** `

I tried putting the actual conf.yml file in several folder locations and tried to map a different location and they all failed.

I think there is confusion within the image looking for a file named "conf.yml" but also trying to look at a folder named "conf.yml" in the coding.

**Comment by holocronology** [comment]
Copying my post from Unraid forum here also:

I think the issue is that when the template runs with the default settings, it is creating a folder named "conf.yml" at /mnt/user/appdata/unraid-simple-monitoring-api/ because the "conf.yml" file doesn't exist.

In my opinion, it would be better to just point to the folder, rather than the file directly. I would change it to:
- container path: /app
- host path: /mnt/user/appdata/unraid-simple-monitoring-api

or

- container path: /app/config
- host path: /mnt/user/appdata/unraid-simple-monitoring-api/config

But. I will try the notes above and let you know if it works.

**Comment by NebN** [comment]
> UPDATE: It works as noted above, but you have to delete the erroneous conf.yml folder that is created by the Unraid template because of the direct file mapping.

This is very interesting, I just completely uninstalled and reinstalled the app, while also removing the conf folder, and it does in fact create a folder named conf.yml upon first installation, which is certainly confusing. This is not something I had noticed in my testing so far.

I'll see what I can do to avoid this in future installations. Thanks for bringing this to my attention!

**Comment by NebN** [comment]
Commit for the proposed change to the app's conf: [link](https://github.com/NebN/unraid-apps/commit/cdb2718b695e53b0efbdff12c2256bbb7ae58a26)
