### ISSUE TITLE
Temperatures

### ISSUE THREAD

**Issue by Th3M1k3y** [NebN/unraid-simple-monitoring-api#20]
Would it be possible to also add temperatures for each hdd and cpu? And maybe other sensors?

**Comment by NebN** [comment]
Someone had already asked this and I completely forgot about it, I will look into it.

**Comment by NebN** [comment]
@Th3M1k3y I have pushed a QA version that is working fine on my Unraid setup, it supports CPU and disk temperatures. 
I don't know if I have made the correct assumptions about general Unraid setups. I would really appreciate it if you could [try out the QA build](https://github.com/NebN/unraid-simple-monitoring-api?tab=readme-ov-file#installing-a-qa-build-) and let me know if it works fine on your machine aswell.

**Comment by Th3M1k3y** [comment]
Tested, and it worked! :)

Got temperature for cpu (4790K), mechanical disk, and from an SSD.

**Comment by NebN** [comment]
Great, thank you. Reopening this so I can close it with the PR to the master branch.
I suggest you switch back to the official build once you see an update for it (shouldn't take long), as it's likely that future QA builds might not work correctly.

**Comment by NebN** [comment]
@Th3M1k3y just a heads up: if you update to v0.3.5, the file being read to return the CPU temperature is going to change. You can keep the software's behaviour exactly the same by specifying the old file in the configuration. Like so:
```yaml
cpuTemp: /sys/class/thermal/thermal_zone1/temp
```
This old file was not working for other users, so the software now either expects it to be specified in the configuration or it is going to attempt to find a suitable file inside of this folder: `/sys/class/hwmon/`
