### ISSUE TITLE
No CPU temp reading

### ISSUE THREAD

**Issue by sausagepimple** [NebN/unraid-simple-monitoring-api#22]
Using this as part of a little desktop app I'm making but am finding that no CPU temps are returned. 
![image](https://github.com/NebN/unraid-simple-monitoring-api/assets/172952005/c305197a-d735-4611-bbc7-5cb4d335b981)

CPU & RAM usage readouts work fine. Just no temp from the CPU.

Temp is reported correctly via UnRaid.

**Comment by NebN** [comment]
Could you please provide the output of the following command:

```
for zone in /sys/class/thermal/thermal_zone*; do
    echo "$zone:"
    cat "$zone/type"
    cat "$zone/temp"
    echo
done
```

Checking the container's logs might also give some useful information: unraid docker tab -> click on application -> logs

**Comment by sausagepimple** [comment]
`/sys/class/thermal/thermal_zone*:
cat: '/sys/class/thermal/thermal_zone*/type': No such file or directory
cat: '/sys/class/thermal/thermal_zone*/temp': No such file or directory`

`2024/06/16 08:47:15 ERROR CPU Cannot read temp data error="open /sys/class/thermal/thermal_zone1/temp: no such file or directory"
2024/06/16 08:47:15 ERROR CPU unable to read /sys/class/thermal/thermal_zone1/temp
2024/06/16 08:47:18 ERROR Disk cannot read path=/mnt/cache error="no such file or directory"
2024/06/16 08:47:18 WARN Disk temperature not set name=""
2024/06/16 08:47:18 WARN Disk aggregation total space is 0, free/used percent will be returned as 0
2024/06/16 08:47:18 ERROR CPU Cannot read temp data error="open /sys/class/thermal/thermal_zone1/temp: no such file or directory"
2024/06/16 08:47:18 ERROR CPU unable to read /sys/class/thermal/thermal_zone1/temp
2024/06/16 08:47:21 ERROR Disk cannot read path=/mnt/cache error="no such file or directory"
2024/06/16 08:47:21 WARN Disk temperature not set name=""
2024/06/16 08:47:21 WARN Disk aggregation total space is 0, free/used percent will be returned as 0
2024/06/16 08:47:21 ERROR CPU Cannot read temp data error="open /sys/class/thermal/thermal_zone1/temp: no such file or directory"
2024/06/16 08:47:21 ERROR CPU unable to read /sys/class/thermal/thermal_zone1/temp
2024/06/16 08:47:24 ERROR Disk cannot read path=/mnt/cache error="no such file or directory"
2024/06/16 08:47:24 WARN Disk temperature not set name=""
2024/06/16 08:47:24 WARN Disk aggregation total space is 0, free/used percent will be returned as 0
2024/06/16 08:47:24 ERROR CPU Cannot read temp data error="open /sys/class/thermal/thermal_zone1/temp: no such file or directory"
2024/06/16 08:47:24 ERROR CPU unable to read /sys/class/thermal/thermal_zone1/temp
2024/06/16 08:47:27 ERROR Disk cannot read path=/mnt/cache error="no such file or directory"
2024/06/16 08:47:27 WARN Disk temperature not set name=""
2024/06/16 08:47:27 WARN Disk aggregation total space is 0, free/used percent will be returned as 0
2024/06/16 08:47:27 ERROR CPU Cannot read temp data error="open /sys/class/thermal/thermal_zone1/temp: no such file or directory"
2024/06/16 08:47:27 ERROR CPU unable to read /sys/class/thermal/thermal_zone1/temp
2024/06/16 08:47:30 ERROR Disk cannot read path=/mnt/cache error="no such file or directory"
2024/06/16 08:47:30 WARN Disk temperature not set name=""
2024/06/16 08:47:30 WARN Disk aggregation total space is 0, free/used percent will be returned as 0
2024/06/16 08:47:30 ERROR CPU Cannot read temp data error="open /sys/class/thermal/thermal_zone1/temp: no such file or directory"
2024/06/16 08:47:30 ERROR CPU unable to read /sys/class/thermal/thermal_zone1/temp
2024/06/16 08:47:33 ERROR Disk cannot read path=/mnt/cache error="no such file or directory"
2024/06/16 08:47:33 WARN Disk temperature not set name=""
2024/06/16 08:47:33 WARN Disk aggregation total space is 0, free/used percent will be returned as 0
2024/06/16 08:47:33 ERROR CPU Cannot read temp data error="open /sys/class/thermal/thermal_zone1/temp: no such file or directory"
2024/06/16 08:47:33 ERROR CPU unable to read /sys/class/thermal/thermal_zone1/temp`

**Comment by NebN** [comment]
Weird, this might be tricky to figure out. I also see some issues while gathering disk info, although it's probably unrelated, and I'm guessing due to a misconfiguration.

Are you using an older version of Unraid by any chance? I'm on 6.12.8 (top left under the Unraid logo).

You mentioned that you are using this software as part of an application you are developing, did you install my software simply by going to the unraid community apps and installing from there?

Could you please provide the following:

- output of this command run on your unraid machine
` ls -l /sys/class/thermal`

- output of this command run on your unraid machine
` ls -l /mnt`

- the json response you see at http://your-unraid-api:24940

- your `unraid-simple-monitoring-api/conf.yml`

**Comment by sausagepimple** [comment]
I basically just used the default config but removed most of the disks. I'm using this API to mainly get memory usage, CPU usage, and hopefully CPU temp.

Yeah I'm making a native MacOS/iPhone app just to give me an overview of the basic metrics off my UnRaid server and give me control over the VMs and Containers hosted on it.

I installed this via the community store, correct. And I'm running UnRaid 6.12.10

`total 0
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device0 -> ../../devices/virtual/thermal/cooling_device0/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device1 -> ../../devices/virtual/thermal/cooling_device1/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device10 -> ../../devices/virtual/thermal/cooling_device10/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device11 -> ../../devices/virtual/thermal/cooling_device11/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device12 -> ../../devices/virtual/thermal/cooling_device12/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device13 -> ../../devices/virtual/thermal/cooling_device13/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device14 -> ../../devices/virtual/thermal/cooling_device14/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device15 -> ../../devices/virtual/thermal/cooling_device15/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device16 -> ../../devices/virtual/thermal/cooling_device16/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device17 -> ../../devices/virtual/thermal/cooling_device17/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device18 -> ../../devices/virtual/thermal/cooling_device18/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device19 -> ../../devices/virtual/thermal/cooling_device19/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device2 -> ../../devices/virtual/thermal/cooling_device2/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device20 -> ../../devices/virtual/thermal/cooling_device20/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device21 -> ../../devices/virtual/thermal/cooling_device21/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device22 -> ../../devices/virtual/thermal/cooling_device22/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device23 -> ../../devices/virtual/thermal/cooling_device23/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device3 -> ../../devices/virtual/thermal/cooling_device3/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device4 -> ../../devices/virtual/thermal/cooling_device4/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device5 -> ../../devices/virtual/thermal/cooling_device5/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device6 -> ../../devices/virtual/thermal/cooling_device6/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device7 -> ../../devices/virtual/thermal/cooling_device7/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device8 -> ../../devices/virtual/thermal/cooling_device8/
lrwxrwxrwx 1 root root 0 Jun 16 02:32 cooling_device9 -> ../../devices/virtual/thermal/cooling_device9/`


`total 32
drwxrwxrwx 9 nobody users 145 Jun 15 06:42 disk1/
drwxrwxrwx 1 nobody users  12 Jun 15 06:40 shares/
drwxrwxrwx 1 nobody users 145 Jun 15 06:42 user/
drwxrwxrwx 1 nobody users 145 Jun 15 06:42 user0/
drwxrwxrwx 1 nobody users  36 Jun 14 00:30 vms/`

**Comment by NebN** [comment]
Temperature readings are a very new feature, and I might have made the wrong assumptions about where to generally find the CPU temp, as in my case it is in a file that you are missing. Another solution is reading files in /sys/class/hwmon/.

Could you please provide the output of the following command? CPU temp should be somewhere in here

```
for dir in /sys/class/hwmon/hwmon*; do
  echo "Directory: $dir"
  for file in $dir/temp*_input; do
    echo "Reading from: $file"
    cat $file
  done
done
```

**Comment by sausagepimple** [comment]
Output here - 

`for dir in /sys/class/hwmon/hwmon*; do
  echo "Directory: $dir"
  for file in $dir/temp*_input; do
    echo "Reading from: $file"
    cat $file
  done
done
Directory: /sys/class/hwmon/hwmon0
Reading from: /sys/class/hwmon/hwmon0/temp1_input
70500
Reading from: /sys/class/hwmon/hwmon0/temp3_input
64500
Reading from: /sys/class/hwmon/hwmon0/temp4_input
70000
Directory: /sys/class/hwmon/hwmon1
Reading from: /sys/class/hwmon/hwmon1/temp1_input
85000
Reading from: /sys/class/hwmon/hwmon1/temp2_input
65000
Reading from: /sys/class/hwmon/hwmon1/temp3_input
59000
Reading from: /sys/class/hwmon/hwmon1/temp4_input
-40000
Reading from: /sys/class/hwmon/hwmon1/temp5_input
0
Directory: /sys/class/hwmon/hwmon2
Reading from: /sys/class/hwmon/hwmon2/temp1_input
65850
Directory: /sys/class/hwmon/hwmon3
Reading from: /sys/class/hwmon/hwmon3/temp1_input
58850
Directory: /sys/class/hwmon/hwmon4
Reading from: /sys/class/hwmon/hwmon4/temp10_input
0
Reading from: /sys/class/hwmon/hwmon4/temp11_input
70500
Reading from: /sys/class/hwmon/hwmon4/temp1_input
59000
Reading from: /sys/class/hwmon/hwmon4/temp2_input
65500
Reading from: /sys/class/hwmon/hwmon4/temp3_input
75500
Reading from: /sys/class/hwmon/hwmon4/temp4_input
59000
Reading from: /sys/class/hwmon/hwmon4/temp5_input
59000
Reading from: /sys/class/hwmon/hwmon4/temp6_input
73000
Reading from: /sys/class/hwmon/hwmon4/temp7_input
65500
Reading from: /sys/class/hwmon/hwmon4/temp8_input
0
Reading from: /sys/class/hwmon/hwmon4/temp9_input
0`

These temps seem accurate to what I was seeing at the time.

**Comment by NebN** [comment]
At a glance they don't seem to be the correct readings, you have a 12 core CPU, so I would expect one section to have 13 inputs, although I admit I am far from knowledgeable in this aspect. Also, the temperatures seem quite high, do you see any that make sense?

For reference, this is the part of my output that is about my 4 core CPU temps (Unraid GUI reads 34°):

```
Directory: /sys/class/hwmon/hwmon1
Reading from: /sys/class/hwmon/hwmon1/temp1_input
34000
Reading from: /sys/class/hwmon/hwmon1/temp2_input
30000
Reading from: /sys/class/hwmon/hwmon1/temp3_input
33000
Reading from: /sys/class/hwmon/hwmon1/temp4_input
32000
Reading from: /sys/class/hwmon/hwmon1/temp5_input
33000
```

And this is my "thermal_zone1" output (the file the software is trying to read):
```
cat /sys/class/thermal/thermal_zone1/temp
33000
```

I am thinking that part of the problem might be that I have an Intel CPU, which probably handles things differently when it comes to temperature sensors. If you are able to find the file to read that contains the correct temperature I'd be happy to implement a fix. As it stands, not having direct access to your setup, it is very difficult for me to find the correct solution.

**Comment by sausagepimple** [comment]
/sys/class/hwmon/hwmon2/temp1_input 65850

Seems most accurate. At the time I was running at 65c because I was running several quite intensive VMs.

**Comment by NebN** [comment]
Alright, I think I have thought of an acceptable solution. I will add an optional entry to the configuration to be able to specify which file contains the cpu temp.

This way each user will be able to adapt the software behavior to their specific setup.

**Comment by sausagepimple** [comment]
Thanks for that!

This has also been super helpful for me learning how to get temps from UnRaid.

**Comment by sausagepimple** [comment]
Great!

After some tweaking it appears the correct temp is from **/sys/class/hwmon/hwmon1/temp2_input**
