### ISSUE TITLE
Parity Information

### ISSUE THREAD

**Issue by Brramble** [NebN/unraid-simple-monitoring-api#25]
Would it be possible to pull the parity drive? Specifically the temperature if possible?

Also, is there any plans to get data from other drives in the cache? As I'm runnning my cache in RAID 1, it would be really nice to get that drive temp too.

**Comment by NebN** [comment]
Getting the parity drive's temp is doable. I'll get on it when I get the chance.

I'm not sure what you mean in regards to the cache, the API is already reading the cache drives' temperature. There is 1 temperature given for both drives in a RAID1 (btrfs) configuration. 
Please note that the temperature can only be read if the drives (array or cache) are not in standby.

Here's an example of what the API is returning for me (4 drives in total, 2 pairs using btrfs):

```json
"cache":[
   {
      "mount":"/mnt/cache",
      "total":931,
      "used":94,
      "free":837,
      "used_percent":10.1,
      "free_percent":89.9,
      "temp":32
   },
   {
      "mount":"/mnt/applications",
      "total":465,
      "used":156,
      "free":309,
      "used_percent":33.55,
      "free_percent":66.45,
      "temp":36
   }
]
```

The data is being read from `/var/local/emhttp/disks.ini`, so any information you find here (like the parity drive's temperature when not in standby) can easily be read and exposed by the API.
