### ISSUE TITLE
Metrics - CPU Core

### ISSUE THREAD

**Issue by sivertheisholt** [NebN/unraid-simple-monitoring-api#30]
Hi! Thank you for creating this.

Is it possible to get information per CPU core? Like this in Unraid:

![image](https://github.com/user-attachments/assets/88f1cb2f-918a-4886-8437-94bae7e71af3)

**Comment by NebN** [comment]
Hello there, I don't see why not, I'll look into it when I get the chance.

**Comment by NebN** [comment]
@sivertheisholt [QA Build](https://github.com/NebN/unraid-simple-monitoring-api?tab=readme-ov-file#installing-a-qa-build-) is available if you'd like to test it or suggest any changes.

![image](https://github.com/user-attachments/assets/f6b001f1-7cb0-4619-b829-5db334d8ef5a)
